name: curs_flutter
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.4
  flutter:
    sdk: flutter
  flutter_redux: ^0.9.0
  http: ^0.13.4
  redux: ^5.0.0
  redux_epics: ^0.15.1
  rxdart: ^0.27.3
  meta: ^1.7.0
  very_good_analysis: ^2.4.0


dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

